### ISSUE TITLE
Error occurred when choice '일반교양'

### ISSUE THREAD

**Issue by RabbitG29** [Agrajak/my-inha-sugang#1]
When I choice '일반교양', there is an error.
There are a few possible timetables, but page says <no timetable>.
When I exclude '일반교양', page works well.

일반교양을 넣었을 때 가능한 시간표가 있음에도 불구하고 없다고 나옴.
제외했을 경우 잘 동작합니다.
안되는 과목조합 예 : 모바일응용소프트웨어설계, 디지털영상처리설계, 정보통신종합설계, 데이터마이닝, 야구소프트볼
되는 과목조합 예 : 위 조합에서 야구소프트볼 제외

**Comment by agrajak** [comment]
필수과목이 보이는 것과 다르게 함수로 넘어가 처리되는 문제가 있었는데 수정!
